version: "2.9"

networks:
  crypto_net:
    name: crypto_net
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/22


services:
  amm_service:
    image: amm
    build:
      context: ./amm
      dockerfile: ./Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - FLASK_SERVER_PORT=8000
    ports:
      - "8000:8000"
    networks:
      crypto_net:
        ipv4_address: 192.168.10.1
    # logging:
    #   driver: "none"


  orcle_service:
    image: oracle
    build:
      context: ./oracle
      dockerfile: ./Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - FLASK_ORACLE_PORT=8000
    ports:
      - "8001:8000"
    networks:
      crypto_net:
        ipv4_address: 192.168.10.2
    logging:
      driver: "none"

  
  node:
    image: node
    build: 
      context: ./node/
      dockerfile: Dockerfile
    depends_on:
      - "amm_service"
    # ports:
    #   - "8802:80"
    networks:
      - crypto_net
    environment:
      - PYTHONUNBUFFERED=1
    cpus: 0.2
    mem_limit: 128MB


  miner:
    image: miner
    build:
      context: ./miner
      dockerfile: ./Dockerfile
    environment:
    - METRICS_FILE=_stats.json
    - BLOCK_CHAIN_FILE=_chain.txt
    # ports:
    #   - "8000:8000"
    networks:
      - crypto_net
    volumes:
      - ./miner:/usr/src/miner