version: "2.9"

networks:
  crypto_net:
    name: crypto_net
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24


services:
  monitor:
    image: monitor
    build:
      context: ./monitor
      dockerfile: ./Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - FLASK_SERVER_PORT=5000
    - AMM_SERVER_ADDR=192.168.10.3
    - AMM_SERVER_PORT=5000
    - ORACLE_SERVER_ADDR=192.168.10.4
    - ORACLE_SERVER_PORT=5000
    ports:
      - 5000:5000
    networks:
      - crypto_net
    # logging:
    #   driver: "none"

  amm_service:
    image: amm
    build:
      context: ./amm
      dockerfile: ./Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - SERVER_PORT=5000
    ports:
      - 5001:5000
    networks:
      crypto_net:
        ipv4_address: 192.168.10.3
    # logging:
    #   driver: "none"


  orcle_service:
    image: oracle
    build:
      context: ./oracle
      dockerfile: ./Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ORACLE_PORT=5000
      - AMM_SERVER_ADDR=192.168.10.3
      - AMM_SERVER_PORT=5000
    ports:
      - 5002:5000
    networks:
      crypto_net:
        ipv4_address: 192.168.10.4
    logging:
      driver: "none"

  
  node:
    image: node
    build: 
      context: ./node/
      dockerfile: Dockerfile
    depends_on:
      - amm_service
    environment:
      - PYTHONUNBUFFERED=1
      - AMM_SERVER_ADDR=192.168.10.3
      - AMM_SERVER_PORT=5000
    networks:
      - crypto_net
    cpus: 0.2
    mem_limit: 128MB


  miner:
    image: miner
    build:
      context: ./miner
      dockerfile: ./Dockerfile
    depends_on:
      - amm_service
    environment:
      - METRICS_FILE=_stats.json
      - BLOCK_CHAIN_FILE=_chain.txt
    networks:
      - crypto_net
    volumes:
      - ./miner:/usr/src/miner