version: "2.9"

networks:
  crypto_net:
    name: crypto_net
    driver: bridge
    ipam:
      config:
        - subnet: 239.192.168.0/24


services:
  miner:
    image: miner
    build:
      context: ./miner
      dockerfile: ./Dockerfile
    environment:
    - METRICS_FILE=_stats.json
    - BLOCK_CHAIN_FILE=_chain.txt
    # ports:
    #   - "8000:8000"
    networks:
      - crypto_net
    volumes:
      - ./miner:/usr/src/miner
      
  # publisher:
  #   image: publisher
  #   build: 
  #     context: ./publisher/
  #     dockerfile: Dockerfile
  #   networks:
  #     - crypto_net
  #   environment:
  #     - PYTHONUNBUFFERED=1

  node:
    image: node
    build: 
      context: ./node/
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - AMM_SERVER_ADDR=192.168.10.3
      - AMM_SERVER_PORT=5000
      - TRANSACTION_BROADCAST=239.192.168.255:5007
      - NODE_BROADCAST=239.192.168.255:5006
    networks:
      - crypto_net
    cpus: 0.2
    mem_limit: 128MB