version: "2.9"

networks:
  crypto_net:
    name: crypto_net
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24


services:
  monitor:
    image: monitor
    build:
      context: ./monitor
      dockerfile: ./Dockerfile
    depends_on:
      - amm_service
      - oracle_service
    environment:
    - PYTHONUNBUFFERED=1
    - FLASK_SERVER_PORT=5000
    - AMM_SERVER_ADDR=192.168.10.3
    - AMM_SERVER_PORT=5000
    - ORACLE_SERVER_ADDR=192.168.10.4
    - ORACLE_SERVER_PORT=5000
    ports:
      - 5000:5000
    networks:
      - crypto_net
    # logging:
    #   driver: "none"

  amm_service:
    image: amm
    build:
      context: ./amm
      dockerfile: ./Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - SERVER_PORT=5000
    - TRANSACTION_BROADCAST=239.192.168.255:5007
    - NODE_BROADCAST=239.192.168.255:5006
    - AMM_SERVER_ADDR=192.168.10.3
    ports:
      - 5001:5000
    networks:
      crypto_net:
        ipv4_address: 192.168.10.3
    volumes:
      - ./amm:/usr/src/app
    # logging:
    #   driver: "none"


  oracle_service:
    image: oracle
    build:
      context: ./oracle
      dockerfile: ./Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ORACLE_PORT=5000
      - AMM_SERVER_ADDR=192.168.10.3
      - AMM_SERVER_PORT=5000
      - APIKEY=a97a2391-8600-4c3e-8dbf-046dd9d86214
    ports:
      - 5002:5000
    networks:
      crypto_net:
        ipv4_address: 192.168.10.4
    logging:
      driver: "none"

  
  node:
    image: node
    build: 
      context: ./node/
      dockerfile: Dockerfile
    depends_on:
      - amm_service
    environment:
      - PYTHONUNBUFFERED=1
      - AMM_SERVER_ADDR=192.168.10.3
      - AMM_SERVER_PORT=5000
      - TRANSACTION_BROADCAST=239.192.168.255:5007
      - NODE_BROADCAST=239.192.168.255:5006
      - SIGNATURE_VERIFY_PORT=5005
    networks:
      - crypto_net
    ports:
      - 5005:5005
    cpus: 0.2
    mem_limit: 128MB


  miner:
    image: miner
    build:
      context: ./miner
      dockerfile: ./Dockerfile
    depends_on:
      - amm_service
    environment:
      - METRICS_FILE=_stats.json
      - BLOCK_CHAIN_FILE=_chain.txt
      - TRANSACTION_BROADCAST=239.192.168.255:5007
      - NODE_BROADCAST=239.192.168.255:5006
      - SIGNATURE_VERIFY_PORT=5005
    networks:
      - crypto_net
    volumes:
      - ./miner:/usr/src/miner